# Creates a release on every version change to the main branch
name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: halvardssm/github-action-tag-release@1.0.0
        with: 
          path: './parcel-reporter-ip/package.json' # optional, will use ./package.json by default
